@extends('layouts.app')

@section('title', 'Privacy Policy - XCLusive Racing')

@section('content')
<main class="xcl-page pb-5 px-3">
    <div class="about-section__topo" style="background-image:url('/topo.png')"></div>

    <div class="container" style="max-width:800px;position:relative;z-index:1">

        <div class="pt-4 mb-5">
            <h1 class="display-5 fw-black text-uppercase fst-italic about-section__heading mb-2">Privacy Policy</h1>
            <div class="section-divider" style="margin-left:0"></div>
            <p class="text-secondary mt-3 mb-0" style="font-size:.9rem">Last updated: {{ date('F j, Y') }}</p>
        </div>

        <div class="d-flex flex-column gap-3">

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">1. Who We Are</h2>
                <p class="text-secondary mb-0" style="line-height:1.8">
                    XCLusive Racing is a sim racing community platform operated by XCLusive Gaming Events.
                    This policy explains what personal data we collect, why we collect it, and how it is used.
                    For any privacy-related questions, reach us on our
                    <a href="{{ config('xcl.discord_url') }}" target="_blank" class="text-decoration-none fw-bold" style="color:#7c3aed">Discord server</a>.
                </p>
            </div>

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">2. What Data We Collect</h2>
                <p class="text-secondary mb-2" style="line-height:1.8">When you create an account we collect:</p>
                <ul class="text-secondary mb-0" style="line-height:2;padding-left:1.25rem">
                    <li>Your name and e-mail address</li>
                    <li>Your gaming platform and platform ID (Steam, Xbox Gamertag, PSN Online ID)</li>
                    <li>Your country</li>
                    <li>Your team name (optional)</li>
                    <li>Connected accounts you choose to link (Discord, Steam, Xbox, PlayStation)</li>
                    <li>Race registrations, results, and XCL Rating history generated by your participation</li>
                </ul>
            </div>

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">3. How We Use Your Data</h2>
                <ul class="text-secondary mb-3" style="line-height:2;padding-left:1.25rem">
                    <li>To create and display your public driver profile</li>
                    <li>To manage event registrations and race results</li>
                    <li>To calculate your XCL Rating and Safety Rating</li>
                    <li>To send event-related notifications (when the e-mail system is active)</li>
                    <li>To enforce platform rules (e.g. suspensions)</li>
                </ul>
                <p class="text-secondary mb-0 fw-bold">We do not sell your data to third parties.</p>
            </div>

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">4. Who Can See Your Data</h2>
                <ul class="text-secondary mb-0" style="line-height:2;padding-left:1.25rem">
                    <li><strong class="text-dark">Public visitors</strong> — can see your driver profile: name, platform, country, XCL Rating and race history</li>
                    <li><strong class="text-dark">Platform admins</strong> — can see all profile data to manage events and enforce rules</li>
                    <li>Your e-mail address and password are never shown publicly</li>
                </ul>
            </div>

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">5. Data Retention</h2>
                <p class="text-secondary mb-0" style="line-height:1.8">
                    Your data is kept for as long as your account is active. If you want your account removed,
                    contact us on Discord and we will delete your personal data within 30 days.
                    Race results may be retained in anonymised form for historical records.
                </p>
            </div>

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">6. Cookies</h2>
                <p class="text-secondary mb-0" style="line-height:1.8">
                    We use only essential session cookies required to keep you logged in.
                    No tracking or advertising cookies are used.
                </p>
            </div>

            <div class="bg-white rounded-3 shadow-sm p-4">
                <h2 class="fw-black text-uppercase text-dark mb-3" style="font-size:.85rem;letter-spacing:.08em">7. Your Rights</h2>
                <p class="text-secondary mb-0" style="line-height:1.8">
                    You have the right to access, correct, or request deletion of your personal data.
                    Contact us via
                    <a href="{{ config('xcl.discord_url') }}" target="_blank" class="text-decoration-none fw-bold" style="color:#7c3aed">Discord</a>
                    to exercise these rights.
                </p>
            </div>

        </div>

    </div>
</main>
@endsection